name: Analizar Partidos Automaticamente
on:
  issues:
    types: [opened]

jobs:
  analizar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Instalar dependencias
        run: |
          pip install pandas numpy scipy
      
      - name: Analizar datos del partido
        run: |
          echo "Analizando partido..."
          echo "${{ github.event.issue.body }}" > datos.txt
          python analizar_partidos.py
      
      - name: Comentar resultados
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Analisis completado. Revisa los resultados.'
            })
